version: '3.0'

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - prometheus_data:/prometheus
    ports:
      - target: 9090
        published: 9090
        mode: host
    user: root
    restart: always
    networks:
        - my_network

networks:
  my_network:

volumes:
  prometheus_data: {}
    
