apiVersion: 1

datasources:
- name: 'prom1'
  type: 'prometheus'
  access: 'proxy'
  org_id: 1
  url: 'http://prometheus:9090'
  is_default: true
  version: 1
  editable: true

- name: MySQL-Airflow
  type: mysql
  url: mysql:3306
  database: airflow
  user: airflow
  password: your_password
  secureJsonData:
    password: your_password
  