version: '3'
services:

  rabbitmq:
    image: 'linsamtw/rabbitmq:14.3.3'
    ports:
      - '5672:5672'
      - '15672:15672'
      # 新增 metrics 的 port，用於監控
      - '15692:15692'
    environment:
      RABBITMQ_DEFAULT_USER: "worker"
      RABBITMQ_DEFAULT_PASS: "worker"
      RABBITMQ_DEFAULT_VHOST: "/"
    # swarm 設定
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.rabbitmq == true]
    networks:
      - my_network

networks:
  my_network:
    # 加入已經存在的網路
    external: true
