version: '3.3'
services:

  mysql:
      image: mysql:8.0
      # 設定 mysql 使用原生認證的密碼 hash
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports: 
        # docker publish port 3306 to 3306 
        # (將 docker 內部 ip 3306, 跟外部 3306 做連結)
          - 3306:3306
        # - target: 3306
        #   published: 3306
        #   mode: host
      environment: # 環境變數, 設置 db, user, password, root_password
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
      volumes:
          - mysql:/var/lib/mysql
          # share volumes of docker container to outside volume, 
          # let data persist
          # 將 docker container 的 volumes 跟外部 volumes 做連結, 
          # 讓資料不會因為, container close or update, 而遺失
      networks:
          - dev

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.0
      links: 
          - mysql:db
      ports:
          - 8000:80
      depends_on:
        - mysql
      networks:
          - dev
     
networks:
  dev:

volumes:
  mysql:
    external: true