version: '3'
services:

  redis:
    image: 'bitnami/redis:5.0'
    ports:
        - 6379:6379
    volumes:
        - 'redis_data:/bitnami/redis/data'
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    networks:
        - dev

  flower:
    image: mher/flower:0.9.5
    command: ["flower", "--broker=redis://redis:6379/0", "--port=5555"]
    ports: # docker publish port 5555 to 5555 (將 docker 內部 ip 5555, 跟外部 5555 做連結)
      - 5555:5555
    depends_on:
      - redis
    networks:
      - dev

networks:
  dev:

volumes:
  redis_data:
