version: '3.0'

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - prometheus_data:/prometheus
    ports:
      - target: 9090
        published: 9090
        mode: host
    user: root
    restart: always
    networks:
        - my_network

  grafana:
    image: grafana/grafana:8.5.25
    ports:
      - target: 3000
        published: 3000
        mode: host
    user: root
    environment:
      # 設定密碼
      - GF_SECURITY_ADMIN_PASSWORD=pass
    restart: always
    networks:
        - my_network

networks:
  my_network:

volumes:
  prometheus_data: {}
    
